### ISSUE TITLE
API-Demo-Test job is failed

### ISSUE THREAD

**Issue by okamara** [qaprosoft/carina-demo#98] opened 2020-04-22 19:35 UTC
Steps:
1. Start API-Demo-Test job from Jenkins
Actual result: Job is faild

Log:
eflections - could not scan file api/users/_delete/rq.json in url file:/opt/jenkins/workspace/okamara/carina-demo/API-Demo-Test/target/test-classes/ with scanner TypeAnnotationsScanner

**Comment by Remox129** [comment] 2020-04-24 16:24
Could you provide the jenkins project configuration?

**Comment by Remox129** [comment] 2020-04-25 04:37
Are you sure it's not a problem with your priveleges? I tested it and it works fine

**Comment by Remox129** [comment] 2020-04-25 04:39
I tested it and it works fine. Could you provide the full log?

**Comment by Remox129** [comment] 2020-04-27 11:39
<img width="1680" alt="Screen Shot 2020-04-27 at 08 38 39" src="https://user-images.githubusercontent.com/18053028/80368088-8e12f100-8862-11ea-8631-7f803361f44b.png">

**Comment by vdelendik** [comment] 2020-04-27 11:40
closing as can't reproduce

**Closed by vdelendik** 2020-04-27 11:40 UTC
Labels: bug
